### ISSUE TITLE
Access to Gitbook as admin for maintainers

### ISSUE THREAD

**Issue by dhonx** [v-community/v_by_example#145]
We have successfully made https://v-community.gitbook.io/v-by-example/, what I am asking now is how we as maintainers can access that. Maybe it could be considered to provide access to other maintainers to https://v-community.gitbook.io/v-by-example/. Thank you...

**Comment by Ivo-Balbaert** [comment]
Hi Don,

 

The only way I can see right now to gain access to editing the gitbook goes as follows:

 

a) start up the website https://v-community.gitbook.io/v-by-example/

b)Press the button "Powered by GitBook in the down-left corner of the page

c) In the new website: click on "Sign in" in the menu

d) Sign in with: Email address:      ivo.balbaert@telenet.be

                                Password:         medved220619!

e) In the page that shows: click on v-by-example

 

Then you get administrative menus on the left and right side.

 

Best regards,

 

Ivo

**Comment by dhonx** [comment]
@Ivo-Balbaert Thanks... I think the best way to post this inside our private discussion.  😁
