### ISSUE TITLE
Chinese version is not show on GitBook

### ISSUE THREAD

**Issue by dhonx** [v-community/v_by_example#157]
After noticing, it looks like the Chinese version is don't appear on our GitBook, I don't know how this happened. 

Can someone investigate this for us?

Sorry, I'm busy with my work at the office. Thank you... 

cc: @stepfencurryxiao

**Comment by StepfenShawn** [comment]
OK, let me try to fix it.

**Comment by dhonx** [comment]
Thanks @stepfencurryxiao  🙂 👍

**Comment by StepfenShawn** [comment]
Oh ! it's like a bug ! Our README.md looks like everything is all right. Other versions can be displayed normally, but the Chinese version cannot be displayed.

**Comment by StepfenShawn** [comment]
I think we should open a label of "help wanted".
