### ISSUE TITLE
Japanese version cannot be displayed on the GitBook

### ISSUE THREAD

**Issue by StepfenShawn** [v-community/v_by_example#165]
Like the Chinese version, the Japanese version cannot be displayed on the GitBook:
https://v-community.gitbook.io/v-by-example/

**Comment by Delta456** [comment]
Yeah, We plan on looking an alternative for Gitbook. I think Gitbook doesn't support Japanese and Chinese but I might be wrong.

Thanks for bringing up though!

**Comment by StepfenShawn** [comment]
Hi @Delta456 ! 
I found that there are no Chinese and Japanese versions in the SUMMARY.md, so I think this may be the reason why the Chinese version and Japanese version cannot be displayed on GitBook.

**Comment by Delta456** [comment]
Nothing changed even after your PR.

**Comment by StepfenShawn** [comment]
@Delta456 Click the directory on the right side of the screen to see the Chinese version and the Japanese version.
![Screenshot from 2020-03-10 20:10:15](https://user-images.githubusercontent.com/44727245/76311626-54b31000-630c-11ea-9ec2-a3362a74923b.png)

**Comment by Delta456** [comment]
Thanks!

**Comment by StepfenShawn** [comment]
You are welcome.
