### ISSUE TITLE
Using GitBook

### ISSUE THREAD

**Issue by Delta456** [v-community/v_by_example#2]
I am thinking of using [Gitbook](https://www.gitbook.com) for V by Examples project because they would be best for browsing online. What you guys think about it?

**Comment by dhonx** [comment]
great idea!! Gitbook is very easy to use.

One question: are you not planning to make your own website for this project ??
if not, for now, Gitbook is a good idea...

**Comment by Delta456** [comment]
@donnisnoni95 I am thinking of using Gitbook for the time being. Gitbook would most probably be replaced by vschool.

**Comment by dhonx** [comment]
@Delta456 Ya surely it will, so I strongly agree to use GitBook for a while until vschool is released in a stable condition

**Comment by vbrazo** [comment]
I created a test account and a page https://app.gitbook.com/@vbrazo/s/v-by-example/ it's good! Let's use Gitbook.

I wonder if we should create something like https://app.gitbook.com/@v-community/s/v-by-example/?

**Comment by vbrazo** [comment]
I created a test account and a page https://app.gitbook.com/@vbrazo/s/v-by-example/ 

I wonder if we should create something like https://app.gitbook.com/@v-community/s/v-by-example/?

**Comment by dhonx** [comment]
@vbrazo ya... it's very easy to use... and it's easy to create what we want to share...

so... let's make an organization account on gitbook... @Delta456 

https://v-community.gitbook.io/v-by-example/ looks good 👍

**Comment by Delta456** [comment]
@vbrazo We should go by the name v_community.

@donnisnoni95 Sure! Looks good to me as well.

**Comment by dhonx** [comment]
@Delta456 ya... agree.. it would be better if you or @vbrazo would make it. if so, let us know.

**Comment by Delta456** [comment]
@donnisnoni95 @vbrazo would be working it.

**Comment by dhonx** [comment]
@Delta456  ok... great. and also consider creating a new channel on discord. Because we don't always talk about trivial things here right ??.

**Comment by Ivo-Balbaert** [comment]
An example of using Gitbook by Crystal: https://crystal-lang.org/reference/

**Comment by dhonx** [comment]
@Ivo-Balbaert thank you for the reference  👍

**Comment by d1y** [comment]
Yes. Now there are too few tutorials in vlang. Deploying them on gitbook will make more developers understand and familiar with vlang.❤️

**Comment by vbrazo** [comment]
Here is the new Discord server: https://discord.gg/d3Qk65J for the V Community. Please go to the `community` channel. Feel free to join us to discuss anything that you consider relevant.

**Comment by dhonx** [comment]
@vbrazo Give it to the README too

**Comment by vbrazo** [comment]
@donnisnoni95 done

**Comment by vbrazo** [comment]
@donnisnoni95 could you push the examples to Gitbook?

**Comment by Ivo-Balbaert** [comment]
I have started work on a Gitbook named: Learn V from Scratch.

**Comment by vbrazo** [comment]
Great! You can lead this @Ivo-Balbaert :)

**Comment by Ivo-Balbaert** [comment]
I could create a separate Gitbook named: V by example. Importing .md pages in Gitbook is straightforward, but there is no synchronization, so perhaps I better wait until the sections have stabilized. What do you guys think?

**Comment by Ivo-Balbaert** [comment]
Sorry my mistake. There is a synchronization possible between a GitHub repo and a Gitbook (https://docs.gitbook.com/integrations/github), so it should be straightforward. I will try this out.

**Comment by vbrazo** [comment]
Access granted. Thanks for doing that @Ivo-Balbaert

**Comment by Ivo-Balbaert** [comment]
Thanks Vitor. 

I am now a step closer in the integration process, but Gitbook is now saying:

 

You must have administrator rights on that repository: v-community/v_by_example

 

If this is not possible, I can fork it, but I presume automatic synchronization is then lost.

 

Would it be possible to give me administrator rights on this repo? I will only use them for for the synchronization with Gitbook.

 

Best regards,

 

Ivo

**Comment by vbrazo** [comment]
@Ivo-Balbaert I've just granted you access. Please use your access wisely. 

.. and go ahead and make it happen. Thanks 👍

**Comment by vbrazo** [comment]
Could you also grant access on the Gitbook project for me and @Delta456? 

We use gmail: swstkbaranwal@ and the other one vbrazo@
