### ISSUE TITLE
Logic is faulty in while loop - conditional_statements.md

### ISSUE THREAD

**Issue by Ivo-Balbaert** [v-community/v_by_example#28]

**Comment by Ivo-Balbaert** [comment]
The code as it is now:

mut factorial := 1
mut counter := 1

for {
	counter++
	factorial=factorial*counter

	if counter > 5 {
		print(factorial)
		break
	}
}
println(counter)

does not print: 120, it prints: 7206
Change the code to the following to print 120:

mut factorial := 1
mut counter := 1

for {
	counter++
	if counter > 5 {
		println(factorial)
		break
	}
        factorial=factorial*counter
}

**Comment by Delta456** [comment]
Hmm, I seem to miss that out.

Thanks for reporting!

**Comment by Delta456** [comment]
This will be fixed in my current PR!

**Comment by Ivo-Balbaert** [comment]
Thanks! Perhaps also reconsider renaming 2. while loop form to 2. for infinite loop form, because V has no while keyword.

Then it would be nice to introduce a 3rd section 3. for condition loop form, with the code:

mut factorial := 1
mut counter := 1

for counter < 5 {
	counter++
        factorial *= counter
}

println(factorial)
println(counter)

producing as output:
//120
//5

**Comment by Delta456** [comment]
Its very similar to `while` form. I have also added infinite `for` loop in current PR.

**Comment by Ivo-Balbaert** [comment]
Thanks!
