### ISSUE TITLE
Logic in for traditional example is not ok - conditional_statements.md

### ISSUE THREAD

**Issue by Ivo-Balbaert** [v-community/v_by_example#29]
The code

mut factorial := 1
mut counter := 1

for i := 0; i < 5; i++ {
	factorial=factorial*counter
	if i == 6 {
		print(factorial)
		continue
	}
	println(i)
}

does not update counter, so factorial is not increased; also i never reaches 6.

The following code:

mut factorial := 1
mut counter := 1

for counter = 1; counter < 6; counter++ {
	factorial=factorial * counter
	if counter == 5 {
		print(factorial)
		continue
	}
	println(counter)
}

produces the desired output:

/*
1
2
3
4
120
*/

**Comment by vbrazo** [comment]
@Ivo-Balbaert thanks for raising the issues and being active in different ways.

We need more people like us and you, so I'm inviting you to our community. Welcome!

**Comment by Ivo-Balbaert** [comment]
Thanks!
