### ISSUE TITLE
Updating Repo structure 

### ISSUE THREAD

**Issue by Delta456** [v-community/v_by_example#3]
I plan on upgrading the repo structure so people can browse easily.

1. First Example
```
- src/
 - chapter/
   - README (the explanation of the example)
   -code/
   -sol/ (solution for the exercise given) 
```
2. Using the old repo structure
```
-src/
 -chapter/
   -README (the explanation of the example)
  - code files with solutions (.v)
```

Any suggestions or ideas are welcome!

**Comment by adlesh** [comment]
I guess my only question is: what goes in the code/ directory within the new repo structure? Is that for the person to store their own code while sol/ has the way you solved it? If so, i think the new structure is fine.

**Comment by Delta456** [comment]
@adlesh 
The code folder will have the whole code which would be explained in README files for anyone who just wants to see the code. Yeah, sol folder has the code how to solve it. I am thinking of merging it into code folder.

**Comment by adlesh** [comment]
Gotcha. Idk if moving them together is necessary. I mean you could do it and just add _solution to the file name, but i could see separate folders being useful when you get to more complex examples.

**Comment by donnisnoni95** [comment]
great idea!!  🙌

**Comment by ylluminate** [comment]
Hmm, I think having too many folders could be overkill... but if you have a lot of examples per chapter, then I suppose this would be good.  I guess it's ultimately up to you in terms of whether you're going to have a lot of micro chapters focused on specific points or fewer chapters with a lot of `code/` contents.

**Comment by dhonx** [comment]
@ylluminate I agree...

**Comment by vbrazo** [comment]
Since we need more people, I'm inviting you guys as members @donnisnoni95 @ylluminate @adlesh to this organization. Thanks for being here!

**Comment by dhonx** [comment]
@vbrazo Thank you... i try my best 🙂🙌

**Comment by vbrazo** [comment]
@donnisnoni95 I see that you do front-end. That's great! We'll need a front-end template for `V by example`. If you see a cool blue template, let us know.

I'm planning to build `vschool`. Vschool will use lessons instead of just examples. For [`Vschool`](https://github.com/v-community/vschool), I wanted to build something like [Elixir School](https://github.com/elixirschool/elixirschool).. which would be a friendly blog maintained by the V community.

**Comment by dhonx** [comment]
Yes, thank you.. 🙂

Yes ... I'm doing a front-end and I'm currently very interested in V.

BTW, Elixir Scholl used Jekyll to build his website and I have little experience with Jekyll. But I will learn that fast (since this is only a static site generator) and surely I will help as much as I can. 

BTW are you have experience with jekyll ?? If so... lets build it... so my job now is just to find a cool blue template  🙂

**Comment by dhonx** [comment]
Still related to this. So, I'm commenting here instead of making a new issue.
How about we rename the `src` folder with a new name. `examples` looks good for me.  🤔

Tag @vbrazo @Delta456 @adlesh @ylluminate

**Comment by vbrazo** [comment]
`examples` would be a good name.

**Comment by dhonx** [comment]
Ya... because with `examples` is one of the main words and main purpose of this project... for me `src` more meaningful to a real application project main source.

**Comment by Delta456** [comment]
I may have a better repo structure in mind so I will soon tell all of you about it soon later (have to do more revisions).

**Comment by dhonx** [comment]
@Delta456 Are you working on it right now ?? If so, tell us all when you are ready.

**Comment by d1y** [comment]
> @Delta456 Are you working on it right now ?? If so, tell us all when you are ready.

If it's a static page, I recommend it: hexo, for our front-end developers, it's a bit more friendly ;>3

**Comment by dhonx** [comment]
ya.. great idea... but they want to using jekyll

**Comment by Delta456** [comment]
Sorry for being late, I have being busy with school.

This is the latest repo structure I have come up with. So what guys you think about of it , also there is gonna be a pdf file for those who want to read it offline.

```
-- main repo
- examples/
- code/
- exercises/
- pdf/
- README.md
- CONTRIBUTING.md
- CODE_OF_CONDUCT.md
- .gitignore
- LICENSE.md 
- `.plan` files
```

**Comment by dhonx** [comment]
LGTM,, just `example`. maybe rename it to `examples` ???

**Comment by vbrazo** [comment]
@Delta456 I like it. It's a pretty good start. Let's execute!

**Comment by Delta456** [comment]
@donnisnoni95 oh yeah that should be `examples`.

**Comment by dhonx** [comment]
@Delta456 So in examples readme will pointing to exercises or ???

**Comment by Delta456** [comment]
@vbrazo Can you work on this?
