### ISSUE TITLE
Plan for november

### ISSUE THREAD

**Issue by vbrazo** [v-community/v_by_example#36]
This issue discusses the items that we want to work in November. 

Please comment below with suggestions.

ps: Please check [our october.plan](https://github.com/v-community/v_by_example/blob/master/october.plan) out to see what we've done so far and get some inspiration.

**Comment by vbrazo** [comment]
I'd consider picking some of these items:

- atomic-counters
- closures
- errors
- http-clients
- http-servers
- json
- maps
- pointers
- reading-files
- regular-expressions
- switch
- testing
- writing-files
- xml

**Comment by vbrazo** [comment]
If I could choose 5, I'd probably go with:
- closures
- errors
- regular-expressions
- testing
- reading and writing files

**Comment by vbrazo** [comment]
I'd consider picking up some of these items:

- errors
- json
- maps
- pointers
- reading files
- switch
- testing
- writing files
- xml

If I could choose 5, I'd probably go with:

- errors
- json
- testing
- reading and writing files
- switch

**Comment by Delta456** [comment]
We still don't have regex and https has some OS related bugs.

**Comment by vbrazo** [comment]
ok! I've just edited my answer. Let me know your thoughts.

**Comment by Delta456** [comment]
- Variables
-  Mutable and Immuable
- Operators (Complete it)
-  Pointers
- Methods
- Generics  
- Strings

I will pick up the above ones

**Comment by vbrazo** [comment]
@ylluminate @Ivo-Balbaert @nedpals @donnisnoni95 thoughts?

**Comment by Ivo-Balbaert** [comment]
errors, in combination with option types is the next important thing I guess

**Comment by dhonx** [comment]
i pick xml

**Comment by Delta456** [comment]
We don't have any library for xml as well.

**Comment by vbrazo** [comment]
Let's build the xml library in another repository? :D

**Comment by dhonx** [comment]
@vbrazo I agree :+1:

**Comment by nedpals** [comment]
very ambitious like alex but ill try the following:
- xml
- lsp (im working on it)
- css
- xpath (as companion for the xml)

not gonna accomplish it all, since there's time for acedemics but yeah i'll do it as much as i can

**Comment by vbrazo** [comment]
Ok awesome!

I'm going to create a new plan file and tag you to review the suggested/planned features. Since we've listed 16 topics, I'm going to split them in 2 months (November and December).

I won't be able to work on any items this week either, because I'm going to be busy with work and an English certificate exam for the canadian immigration. After that I'll be on vacations for 1 week and while I'm on vacations, I'll jump back on the examples. 

Thanks guys!

**Comment by vbrazo** [comment]
Please review: https://github.com/v-community/v_by_example/pull/40.
