### ISSUE TITLE
Define a release process

### ISSUE THREAD

**Issue by vbrazo** [v-community/v_by_example#4]
## Checklist
- [x] Add `CHANGELOG.md`
- [x] Start following a release process pattern pattern and do GitHub releases with a single responsibility

I'd consider using `Rubygems.org` pattern: https://guides.rubygems.org/patterns/#semantic-versioning. A release can contain 1 or more PRs depending on the amount of work required to satisfy the responsibility.

**Comment by vbrazo** [comment]
My opinion is that typos and documentation shouldn't require a version bump. Only when we have bugs or add/remove examples.

**Comment by dhonx** [comment]
Maybe ... but that might help us jump into previous versions/releases. 🤔
