### ISSUE TITLE
How Typo CI actually works 

### ISSUE THREAD

**Issue by dhonx** [v-community/v_by_example#76]
Notice that Typo CI check every commit... not every PR
so we need to work directly on base repo instead of the forked repo to get the advantage of Typo CI
OMG ... why did I just realize this ??? :smile:

**Comment by vbrazo** [comment]
@MikeRogers0 tagging you in this post to discuss this potential issue with Don. Thanks!

**Comment by MikeRogers0** [comment]
Happy to help sort this for you :)

https://github.com/v-community/v_by_example/pull/73/checks - I'm looking at this one to figure out why it didn't kick it :) It might take me a until the weekend to sort, I'm slammed pretty hard at work right now :)

**Comment by dhonx** [comment]
@MikeRogers0 Thank you, man ... Typo CI really helped us to check typo ... I was confused about why this didn't work. I think maybe in `typo-ci.yml` or something ... I just realized it when @vbrazo works directly in the repo base ... and I'm surprised .. how come this one works ??

It's fine if you're busy... don't overexert yourself because of this. If you have free time try to fix it. And I hope as soon as possible.  ✌️ 👍

**Comment by vbrazo** [comment]
@MikeRogers0 I think Typo CI should also ignore `V` keywords by default. This repository has the keywords. Check [them](https://github.com/v-community/v_by_example/blob/master/examples/keywords.md) out.

**Comment by MikeRogers0** [comment]
@vbrazo I'll add them in :)

Edit: Done :)

**Comment by MikeRogers0** [comment]
Just a heads up, I've pushed an update to Typo CI that should solve issue of PRs from forked repos not being checked :)

I really appreciate your help with this one, if we ever cross paths I'll happily buy you all a beverage of your choosing :)

**Comment by dhonx** [comment]
Your welcome man... actually we help each other though. Very glad it now works. I hope we will meet each other someday 😊

See https://github.com/v-community/v_by_example/pull/79. Thank you so much @MikeRogers0  👍 👌
