### ISSUE TITLE
Update creating an empty array section

### ISSUE THREAD

**Issue by dhonx** [v-community/v_by_example#78]
Due to this commit
https://github.com/vlang/v/commit/5df5f97daf55da97ceb1915995536a7e1c9472f8

Now we can create an empty array without having to declare the string after it. Please update the [Array](https://github.com/v-community/v_by_example/blob/master/examples/arrays/arrays.md)

**Comment by spmse** [comment]
I would do that, just one question according the output format: Is there a decision yet which output format to use? 

Just asking because this was a discussion point with #88 and I also could change the output format.
