### ISSUE TITLE
Make hello world example more simpler

### ISSUE THREAD

**Issue by dhonx** [v-community/v_by_example#8]
I think the code inside `hello_world.v` is a bit complex there. because the name is `hello world`.
I think we can make this simpler by changing some code. 🤔

- `struct` might be better to have its own example 
- it would be better if we did not involve the `variables` there.
- only `comments` and `print` stuff there.

Not all people who want to learn V are people who do not have prior programming skills. Maybe they are new to programming. We don't know, but it would be better to start with something simple. So everyone can learn easily.   😊 ✌️

@vbrazo @Delta456 @ylluminate

**Comment by Delta456** [comment]
Yeah you are right. I have changed everything so wait for my next PR :smiley:

**Comment by dhonx** [comment]
Great!!, I am very excited about what we will do next !!  😊

**Comment by d1y** [comment]
Yes. I think You should write the usage of the `main` function in `hello world`.

```go
/*
** the main() is The main function will run automatically,
** just like the go language mechanism
*/
fn main() {
  println('hello world') // the print in `string`
}

```

**Comment by dhonx** [comment]
@d1y Good idea..!!!

**Comment by vbrazo** [comment]
Is this issue resolved? If so, please close it.

**Comment by Delta456** [comment]
Done
