### ISSUE TITLE
Use V or Go for Syntax Highlighting

### ISSUE THREAD

**Issue by spmse** [v-community/v_by_example#92]
We can use V syntax highlighting here in the fenced markdown code parts.
Update example files to have V highlighting instead of Go.

**Comment by dhonx** [comment]
I reopened this issue because for now, V syntax highlighting not working on gitbook. So I want we discuss this. Are we choosing to Go or V for syntax highlighting ??

**Comment by spmse** [comment]
> I reopened this issue because for now, V syntax highlighting not working on gitbook. So I want we discuss this. Are we choosing to Go or V for syntax highlighting ??

I tend to say Go (but I would love using V), because this repositories intention is to create the GitBook isn't it? 

Is there a way to create the GitBook from alternative source-files where we use Go highlighting instead of V? Because then we could create documentation and files here with V-highlighting and build it with Go highlighting

**Comment by dhonx** [comment]
> I tend to say Go (but I would love using V), because this repositories intention is to create the GitBook isn't it?

Yeah... 

> Is there a way to create the GitBook from alternative source-files where we use Go highlighting instead of V?

I don't know exactly. But AFAIK we use webhook to notify GitBook too update the docs

**Comment by vbrazo** [comment]
We should probably send GitBook an email asking them to add the V highlighting because GitHub has already done it.

**Comment by dhonx** [comment]
@GitbookIO

**Comment by Delta456** [comment]
No, let's just use Go for syntax highlighting now. We will need it till markdown universal will have support for V .

**Comment by dhonx** [comment]
Yeah, another reason why I want using Go is because of VSCode not support V syntax highlighting on MD yet

**Comment by dhonx** [comment]
#100
