### ISSUE TITLE
Conditional statements is triplicated in GitBook left menu

### ISSUE THREAD

**Issue by vbrazo** [v-community/v_by_example#99]
I see that GitBook is displaying 3 conditional statements in the left menu.

<img width="1440" alt="Screen Shot 2019-12-04 at 12 57 49 AM" src="https://user-images.githubusercontent.com/1292556/70128240-5eecb080-1631-11ea-943c-30c05e82a62a.png">

We should fix this.

**Comment by dhonx** [comment]
Hahaha... i just mention you on last merged PR about this :smile:

**Comment by vbrazo** [comment]
Yeah! Maintainers' thoughts have synergy.

**Comment by dhonx** [comment]
I'm a bit of a dilemma with this:
- Combine the two of them.
- Or the `Match Statement` stands alone.

Hmmmm... ?? :thinking:

**Comment by vbrazo** [comment]
I'd vote to merge them.

**Comment by vbrazo** [comment]
The design looks nicer. Who improved it?

**Comment by dhonx** [comment]
Agreed.....

Maybe @Ivo-Balbaert I think

**Comment by vbrazo** [comment]
We should divide these examples in chapters and name them.

<img width="137" alt="Screen Shot 2019-12-04 at 11 03 43 AM" src="https://user-images.githubusercontent.com/1292556/70172589-d3513f00-1685-11ea-9e4a-b659f1916e51.png">

I'd consider starting with 3 or 4 chapters.
